name: sams
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_plugin_android_lifecycle: ^2.0.24
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  image_picker: ^1.0.4
  excel: ^4.0.6
  pdf: ^3.11.3
  open_file: ^3.5.10
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  appwrite: ^15.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"